### ISSUE TITLE
Ajout 5

### ISSUE THREAD

**Issue by Raushka** [inventaire-des-orgues/indexes#10]
Il faut ajouter un orgue de cœur que se trouve à l'église l "Église Reformée ", Troyes, Aube
INSEE 10317

**Comment by GwilhermPoullennec** [comment]
FR-10387-TROYE-PROTES1-C
https://inventaire-des-orgues.fr/detail/orgue-troyes-eglise-reformee-fr-10387-troye-protes1-c/
