### ISSUE TITLE
Orgues manquant inventaire pays de la Loire

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/indexes#160]
- Maine-et-Loire 49 : Noyant,  Eglise Saint Martin, orgue de choeur 8 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=44
- Loire-Atlantique 44 : La Planche, Eglise Saint Jacques, Grand orgue 8 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=52
- Vendée 85 : Olonne sur mer, Eglise Notre Dame de l'Assomption, Grand de choeur, 18 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=55
- Vendée 85 :  La Roche-sur-Yon, Conservatoire à Rayonnement Départemental, Orgue d'étude, 4 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=117
- Loire-Atlantique 44 : La Chapelle-sur-Erdre, Église Sainte-Catherine, Grand Orgue, 24 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=119
- Maine-et-Loire (49), Saumur, Église Notre-Dame-des-Ardilliers, Orgue de Choeur, 7 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=127
- Loire-Atlantique 44 : Saint-Nazaire, Église Notre-Dame d'Espérance, Grand Orgue, 7 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=141
- Maine de Loire 49 : le marillais, Sanctuaire Notre Dame, Grand Orgue, 15 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=150
- Vendée 85 : Saint-Hilaire-de-Riez, Eglise Saint Hilaire, Orgue de Choeur, 3 jeux, http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=151
- 
Corrections :
- Nantes Saint **Similien** (dans la base Simllien : 2 LL) : https://inventaire-des-orgues.fr/detail/orgue-nantes-eglise-saint-simllien-fr-44109-nante-stsiml1-x/ 
- Saint Nazaire Saint **Anne** (dans la base Saint Arme)
https://inventaire-des-orgues.fr/detail/orgue-saint-nazaire-eglise-sainte-arme-fr-44184-ssnaz-starme1-x/
- Saint nazaire, Eglise Saint Joseph de Méan
https://inventaire-des-orgues.fr/detail/orgue-saint-nazaire-eglise-de-mean-fr-44184-ssnaz-meannn1-p/

**Comment by GwilhermPoullennec** [comment]
- Nantes Saint Similien (dans la base Simllien : 2 LL) : https://inventaire-des-orgues.fr/detail/orgue-nantes-eglise-saint-simllien-fr-44109-nante-stsiml1-x/
    - Saint Nazaire Saint Anne (dans la base Saint Arme)
    https://inventaire-des-orgues.fr/detail/orgue-saint-nazaire-eglise-sainte-arme-fr-44184-ssnaz-starme1-x/
    - Saint nazaire, Eglise Saint Joseph de Méan
    https://inventaire-des-orgues.fr/detail/orgue-saint-nazaire-eglise-de-mean-fr-44184-ssnaz-meannn1-p/

FAIT

**Comment by GwilhermPoullennec** [comment]
Maine-et-Loire 49 : Noyant, Eglise Saint Martin, orgue de choeur 8 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=44

FAIT

**Comment by GwilhermPoullennec** [comment]
Loire-Atlantique 44 : La Planche, Eglise Saint Jacques, Grand orgue 8 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=52

Vendée 85 : Olonne sur mer, Eglise Notre Dame de l'Assomption, Grand de choeur, 18 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=55

Vendée 85 : La Roche-sur-Yon, Conservatoire à Rayonnement Départemental, Orgue d'étude, 4 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=117

Loire-Atlantique 44 : La Chapelle-sur-Erdre, Église Sainte-Catherine, Grand Orgue, 24 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=119

Maine-et-Loire (49), Saumur, Église Notre-Dame-des-Ardilliers, Orgue de Choeur, 7 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=127

**Comment by GwilhermPoullennec** [comment]
Loire-Atlantique 44 : Saint-Nazaire, Église Notre-Dame d'Espérance, Grand Orgue, 7 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=141
Maine de Loire 49 : le marillais, Sanctuaire Notre Dame, Grand Orgue, 15 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=150
Vendée 85 : Saint-Hilaire-de-Riez, Eglise Saint Hilaire, Orgue de Choeur, 3 jeux, http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=151

**Comment by GwilhermPoullennec** [comment]
Tout fait.

**Comment by patou** [comment]
Merci

**Comment by patou** [comment]
@GwilhermPoullennec Il manque celui là :
Maine de Loire 49 : le marillais, Sanctuaire Notre Dame, Grand Orgue, 15 jeux http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=150

**Comment by patou** [comment]
> ```
> - Nantes Saint Similien (dans la base Simllien : 2 LL) : https://inventaire-des-orgues.fr/detail/orgue-nantes-eglise-saint-simllien-fr-44109-nante-stsiml1-x/
> - Saint Nazaire Saint Anne (dans la base Saint Arme)
> https://inventaire-des-orgues.fr/detail/orgue-saint-nazaire-eglise-sainte-arme-fr-44184-ssnaz-starme1-x/
> - Saint nazaire, Eglise Saint Joseph de Méan
> https://inventaire-des-orgues.fr/detail/orgue-saint-nazaire-eglise-de-mean-fr-44184-ssnaz-meannn1-p/
> ```
> 
> FAIT

Après ça sera à voir avec la possibilité de modifier le slug, car les urls ont toujours les fautes du coup.

**Comment by GwilhermPoullennec** [comment]
>@GwilhermPoullennec Il manque celui là : ...

@patou si, il est à Mauges-sur-Loire

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GwilhermPoullennec** [comment]
>> ``` ...

@patou oui, c’est pour cela que l’on ne coupera pas à la violence de rompre quelques liens...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patou** [comment]
> Mauges-sur-Loire

Ok, vu, J'avais cherché Marillais et Santuaire notre dame.
