### ISSUE TITLE
Sainte Foy de Conques : manque orgue

### ISSUE THREAD

**Issue by Archiv0lte** [inventaire-des-orgues/indexes#219]
Bonjour,
L'inventaire fait référence à un seul orgue à Sainte Foy. Or il y en a deux.
Les informations sur ces instruments sont disponibles ici : https://orguesdeconques.frama.site/
Merci pour ce beau travail fort utile pour nous autres organistes.
Très cordialement,
E.D.

**Comment by patou** [comment]
Le site n'est plus disponible.
