### ISSUE TITLE
Geolocalisation : finir

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/indexes#239]

**Comment by CelestinHuet** [comment]
Lancer l’appariement sur tous les orgues qui n’ont pas déjà le champ id_osm rempli :
py manage.py appariement_osm all

Associer à chaque orgue les id d’OSM trouvés dans appariement_osm :
py manage.py import_organ_osm_id orgues/appariement/appariements_osm_all.json


Calculer le barycentre de chaque bâtiment. On recalcule pour tous les orgues, mais cela permet de corriger les orgues pour lesquels la position est erronée pour le moment :
py manage.py calcul_barycenter_osm --calculall calculall

Associer à chaque orgue les positions en latitude longitude calculées dans calcul_barycenter_osm :
py manage.py import_organ_lonlat coordonnees_osm.json --ecrase if


A condition qu’on ne lance pas appariement_osm et calcul_barycenter_osm le même jour, on sera en-dessous de la limite des 10000 requêtes par jour.

**Comment by GwilhermPoullennec** [comment]
Le premier script appariement_osm all est en train de tourner.

**Comment by GwilhermPoullennec** [comment]
Nota : j'ai copié les commandes dans le README.md principal du projet
https://github.com/inventaire-des-orgues/portail/blob/master/README.md
