### ISSUE TITLE
Le grand orgue de la basilique de Rennes est en double

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/indexes#304]
https://inventaire-des-orgues.fr/detail/orgue-rennes-basilique-saint-sauveur-fr-35238-renne-stsauv-t/

https://inventaire-des-orgues.fr/detail/orgue-rennes-basilique-saint-sauveur-fr-35238-renne-stsauv1-t/

Dans la première fiche, il y a les liens vers l'inventaire des monuments historiques, mais pas le pdf de l'inventaire papier
Dans la deuxième fiche, c'est l'inverse.

**Comment by GwilhermPoullennec** [comment]
PM Palissy ajoutés à la fiche STSAUV1 et fiche STSAUV supprimée.
